<?php
//---------------------------------------------------------------
# create flexible content blocks
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_58ae20cb7886a',
  'title' => 'Page Layout Options',
  'fields' => array (
    array (
      'key' => 'field_58ae20dd743ff',
      'label' => 'Page Flex Content',
      'name' => 'page_flex_content',
      'type' => 'flexible_content',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Add Layout Section',
      'min' => '',
      'max' => '',
      'layouts' => array (
        array (
          'key' => '58ae772b0de81',
          'name' => 'one_column',
          'label' => 'One Column',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_58ae77590de84',
              'label' => 'Column1',
              'name' => 'column1',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58ae77340de82',
          'name' => 'two_columns',
          'label' => 'Two Columns',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_58ae776d0de85',
              'label' => 'Column1',
              'name' => 'column1',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58ae777a0de86',
              'label' => 'Column2',
              'name' => 'column2',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58ae77390de83',
          'name' => 'three_columns',
          'label' => 'Three Columns',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_58ae77970de87',
              'label' => 'Column1',
              'name' => 'column1',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58ae77aa0de88',
              'label' => 'Column2',
              'name' => 'column2',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58ae77b50de89',
              'label' => 'Column3',
              'name' => 'column3',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58bdbc5da9267',
          'name' => 'two_columns_sidebar_right',
          'label' => 'Two Columns Sidebar Right',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_58bdbcafa9268',
              'label' => 'Column1',
              'name' => 'column1',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '66.6666',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58bdbcc7a9269',
              'label' => 'Column2',
              'name' => 'column2',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58bdbcdca926a',
          'name' => 'two_columns_sidebar_left',
          'label' => 'Two Columns Sidebar Left',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_58bdbce7a926b',
              'label' => 'Column1',
              'name' => 'column1',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58bdbcf5a926c',
              'label' => 'Column2',
              'name' => 'column2',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '66.6666',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58ae71ea6bc62',
          'name' => 'hero_slider',
          'label' => 'Hero Slider',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_58ae72006bc63',
              'label' => 'Slides',
              'name' => 'slides',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => 'field_58ae72156bc64',
              'min' => 0,
              'max' => 0,
              'layout' => 'table',
              'button_label' => 'Add Slide',
              'sub_fields' => array (
                array (
                  'key' => 'field_58ae72156bc64',
                  'label' => 'Slide Title',
                  'name' => 'slide_title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_58ae721f6bc65',
                  'label' => 'Slide Link',
                  'name' => 'slide_link',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                ),
                array (
                  'key' => 'field_58ae724d6bc66',
                  'label' => 'Slide Image',
                  'name' => 'slide_image',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
                array (
                  'key' => 'field_58ae725e6bc67',
                  'label' => 'Slide Description',
                  'name' => 'slide_description',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => 'wpautop',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_58af4e3956e9c',
                  'label' => 'Slide Background',
                  'name' => 'slide_background',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => '',
                  'conditional_logic' => '',
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
              ),
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58ae20f3f4086',
          'name' => 'triple_stacked_tiles',
          'label' => 'Triple Stacked Tiles',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_58ae219174400',
              'label' => 'Tile 1 Title',
              'name' => 'tile_1_title',
              'type' => 'text',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_58ae21a774401',
              'label' => 'Tile 2 Title',
              'name' => 'tile_2_title',
              'type' => 'text',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_58ae21aa74402',
              'label' => 'Tile 3 Title',
              'name' => 'tile_3_title',
              'type' => 'text',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_58ae22bc74406',
              'label' => 'Tile 1 Description',
              'name' => 'tile_1_description',
              'type' => 'textarea',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'new_lines' => '',
              'maxlength' => '',
              'placeholder' => '',
              'readonly' => 0,
              'disabled' => 0,
              'rows' => '',
            ),
            array (
              'key' => 'field_58ae22d474407',
              'label' => 'Tile 2 Description',
              'name' => 'tile_2_description',
              'type' => 'textarea',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'new_lines' => '',
              'maxlength' => '',
              'placeholder' => '',
              'readonly' => 0,
              'disabled' => 0,
              'rows' => '',
            ),
            array (
              'key' => 'field_58ae22d674408',
              'label' => 'Tile 3 Description',
              'name' => 'tile_3_description',
              'type' => 'textarea',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'new_lines' => '',
              'maxlength' => '',
              'placeholder' => '',
              'readonly' => 0,
              'disabled' => 0,
              'rows' => '',
            ),
            array (
              'key' => 'field_58ae21ef74403',
              'label' => 'Tile 1 Link',
              'name' => 'tile_1_link',
              'type' => 'url',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
            array (
              'key' => 'field_58ae228c74404',
              'label' => 'Tile 2 Link',
              'name' => 'tile_2_link',
              'type' => 'url',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
            array (
              'key' => 'field_58ae228d74405',
              'label' => 'Tile 3 Link',
              'name' => 'tile_3_link',
              'type' => 'url',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58ae235c74409',
          'name' => 'dual_promo_tiles',
          'label' => 'Dual Promo Tiles',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_58ae23a87440c',
              'label' => 'Tile 1 Background Image',
              'name' => 'tile_1_image',
              'type' => 'image',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => 0,
              'min_height' => 0,
              'min_size' => 0,
              'max_width' => 0,
              'max_height' => 0,
              'max_size' => 0,
              'mime_types' => '',
            ),
            array (
              'key' => 'field_58ae24877440d',
              'label' => 'Tile 2 Background Image',
              'name' => 'tile_2_image',
              'type' => 'image',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => 0,
              'min_height' => 0,
              'min_size' => 0,
              'max_width' => 0,
              'max_height' => 0,
              'max_size' => 0,
              'mime_types' => '',
            ),
            array (
              'key' => 'field_58ae23797440a',
              'label' => 'Tile 1 Title',
              'name' => 'tile_1_title',
              'type' => 'text',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_58ae23887440b',
              'label' => 'Tile 2 Title',
              'name' => 'tile_2_title',
              'type' => 'text',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_58ae24997440e',
              'label' => 'Tile 1 Description',
              'name' => 'tile_1_description',
              'type' => 'textarea',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'new_lines' => '',
              'maxlength' => '',
              'placeholder' => '',
              'readonly' => 0,
              'disabled' => 0,
              'rows' => '',
            ),
            array (
              'key' => 'field_58ae24aa7440f',
              'label' => 'Tile 2 Description',
              'name' => 'tile_2_description',
              'type' => 'textarea',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'new_lines' => '',
              'maxlength' => '',
              'placeholder' => '',
              'readonly' => 0,
              'disabled' => 0,
              'rows' => '',
            ),
            array (
              'key' => 'field_58ae255474410',
              'label' => 'Tile 1 Link',
              'name' => 'tile_1_link',
              'type' => 'url',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
            array (
              'key' => 'field_58ae256374411',
              'label' => 'Tile 2 Link',
              'name' => 'tile_2_link',
              'type' => 'url',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58ae257974412',
          'name' => 'testimonial_slider',
          'label' => 'Testimonial Slider',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_58ae258574413',
              'label' => 'Info',
              'name' => '',
              'type' => 'message',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => 'Nothing to do here; this layout is automated.',
              'new_lines' => 'wpautop',
              'esc_html' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;
