<?php
//---------------------------------------------------------------
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_58ae20cb7886a',
  'title' => 'Page Layout Options',
  'fields' => array (
    array (
      'key' => 'field_58ae20dd743ff',
      'label' => 'Page Flex Content',
      'name' => 'page_flex_content',
      'type' => 'flexible_content',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Add Layout Section',
      'min' => '',
      'max' => '',
      'layouts' => array (
        array (
          'key' => '58ae772b0de81',
          'name' => 'one_column',
          'label' => 'One Column',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_59665d0254437',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_58ae77590de84',
              'label' => 'Column1',
              'name' => 'column1',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58be01c36acc9',
              'label' => 'Space Before',
              'name' => 'space_before',
              'type' => 'select',
              'instructions' => 'To include space before this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_58be01cd6acca',
              'label' => 'Space After',
              'name' => 'space_after',
              'type' => 'select',
              'instructions' => 'To include space after this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_59665c4e54436',
              'label' => 'Section Highlight',
              'name' => 'section_highlight',
              'type' => 'select',
              'instructions' => 'To show a color highlight behind this layout section, select the theme here.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'none',
                'theme_primary' => 'theme_primary',
                'theme_secondary' => 'theme_secondary',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58ae77340de82',
          'name' => 'two_columns',
          'label' => 'Two Columns',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_59665d3b54438',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_58ae776d0de85',
              'label' => 'Column1',
              'name' => 'column1',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58ae777a0de86',
              'label' => 'Column2',
              'name' => 'column2',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58bdff7c6acb8',
              'label' => 'Space Before',
              'name' => 'space_before',
              'type' => 'select',
              'instructions' => 'To include space before this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_58bdffb86acb9',
              'label' => 'Space After',
              'name' => 'space_after',
              'type' => 'select',
              'instructions' => 'To include space after this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_59665d4754439',
              'label' => 'Section Highlight',
              'name' => 'section_highlight',
              'type' => 'select',
              'instructions' => 'To show a color highlight behind this layout section, select the theme here.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'none',
                'theme_primary' => 'theme_primary',
                'theme_secondary' => 'theme_secondary',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58ae77390de83',
          'name' => 'three_columns',
          'label' => 'Three Columns',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_59665d585443a',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_58ae77970de87',
              'label' => 'Column1',
              'name' => 'column1',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58ae77aa0de88',
              'label' => 'Column2',
              'name' => 'column2',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58ae77b50de89',
              'label' => 'Column3',
              'name' => 'column3',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58be006c6acba',
              'label' => 'Space Before',
              'name' => 'space_before',
              'type' => 'select',
              'instructions' => 'To include space before this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_58be00b06acbc',
              'label' => 'Space After',
              'name' => 'space_after',
              'type' => 'select',
              'instructions' => 'To include space after this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_59665d755443b',
              'label' => 'Section Highlight',
              'name' => 'section_highlight',
              'type' => 'select',
              'instructions' => 'To show a color highlight behind this layout section, select the theme here.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'none',
                'theme_primary' => 'theme_primary',
                'theme_secondary' => 'theme_secondary',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58bdbc5da9267',
          'name' => 'two_columns_sidebar_right',
          'label' => 'Two Columns Sidebar Right',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_59665d885443c',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_58bdbcafa9268',
              'label' => 'Column1',
              'name' => 'column1',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '66.6666',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58bdbcc7a9269',
              'label' => 'Column2',
              'name' => 'column2',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58be00bb6acbd',
              'label' => 'Space Before',
              'name' => 'space_before',
              'type' => 'select',
              'instructions' => 'To include space before this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_58be00c46acbe',
              'label' => 'Space After',
              'name' => 'space_after',
              'type' => 'select',
              'instructions' => 'To include space after this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_59665d935443d',
              'label' => 'Section Highlight',
              'name' => 'section_highlight',
              'type' => 'select',
              'instructions' => 'To show a color highlight behind this layout section, select the theme here.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'none',
                'theme_primary' => 'theme_primary',
                'theme_secondary' => 'theme_secondary',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58bdbcdca926a',
          'name' => 'two_columns_sidebar_left',
          'label' => 'Two Columns Sidebar Left',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_59665da25443e',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_58bdbce7a926b',
              'label' => 'Column1',
              'name' => 'column1',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '33.3333',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58bdbcf5a926c',
              'label' => 'Column2',
              'name' => 'column2',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '66.6666',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_58be00ce6acbf',
              'label' => 'Space Before',
              'name' => 'space_before',
              'type' => 'select',
              'instructions' => 'To include space before this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_58be00da6acc0',
              'label' => 'Space After',
              'name' => 'space_after',
              'type' => 'select',
              'instructions' => 'To include space after this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_59665db15443f',
              'label' => 'Section Highlight',
              'name' => 'section_highlight',
              'type' => 'select',
              'instructions' => 'To show a color highlight behind this layout section, select the theme here.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'none',
                'theme_primary' => 'theme_primary',
                'theme_secondary' => 'theme_secondary',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58ae71ea6bc62',
          'name' => 'hero_slider',
          'label' => 'Hero Slider',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_58ae72006bc63',
              'label' => 'Slides',
              'name' => 'slides',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => 'field_58ae72156bc64',
              'min' => 0,
              'max' => 0,
              'layout' => 'table',
              'button_label' => 'Add Slide',
              'sub_fields' => array (
                array (
                  'key' => 'field_58ae72156bc64',
                  'label' => 'Slide Title',
                  'name' => 'slide_title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_58ae721f6bc65',
                  'label' => 'Slide Link',
                  'name' => 'slide_link',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                ),
                array (
                  'key' => 'field_58ae724d6bc66',
                  'label' => 'Slide Image',
                  'name' => 'slide_image',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
                array (
                  'key' => 'field_58ae725e6bc67',
                  'label' => 'Slide Description',
                  'name' => 'slide_description',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => 'wpautop',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_58af4e3956e9c',
                  'label' => 'Slide Background',
                  'name' => 'slide_background',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => '',
                  'conditional_logic' => '',
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
              ),
            ),
            array (
              'key' => 'field_58be00e66acc1',
              'label' => 'Space Before',
              'name' => 'space_before',
              'type' => 'select',
              'instructions' => 'To include space before this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_58be00f06acc2',
              'label' => 'Space After',
              'name' => 'space_after',
              'type' => 'select',
              'instructions' => 'To include space after this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_59665dc254440',
              'label' => 'Section Highlight',
              'name' => 'section_highlight',
              'type' => 'select',
              'instructions' => 'To show a color highlight behind this layout section, select the theme here.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'none',
                'theme_primary' => 'theme_primary',
                'theme_secondary' => 'theme_secondary',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58ae20f3f4086',
          'name' => 'accordion_group',
          'label' => 'Accordion Group',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_59665dd654441',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_58d6e808718b0',
              'label' => 'Panels',
              'name' => 'panels',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 0,
              'max' => 0,
              'layout' => 'table',
              'button_label' => 'Add Panel',
              'sub_fields' => array (
                array (
                  'key' => 'field_58d6ea23718b1',
                  'label' => 'Panel Title',
                  'name' => 'panel_title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => '',
                  'conditional_logic' => '',
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_58d6ef5c718b2',
                  'label' => 'Panel Content',
                  'name' => 'panel_content',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => '',
                  'conditional_logic' => '',
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'full',
                  'media_upload' => '',
                  'delay' => 0,
                ),
                array (
                  'key' => 'field_58d6ef67718b3',
                  'label' => 'Panel Open by Default',
                  'name' => 'panel_open_by_default',
                  'type' => 'true_false',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'message' => 'This panel should be open by default.',
                  'default_value' => 0,
                  'ui' => 1,
                  'ui_on_text' => 'Open',
                  'ui_off_text' => 'Closed',
                ),
              ),
            ),
            array (
              'key' => 'field_58be00fc6acc3',
              'label' => 'Space Before',
              'name' => 'space_before',
              'type' => 'select',
              'instructions' => 'To include space before this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_58be01116acc4',
              'label' => 'Space After',
              'name' => 'space_after',
              'type' => 'select',
              'instructions' => 'To include space after this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_59665de254442',
              'label' => 'Section Highlight',
              'name' => 'section_highlight',
              'type' => 'select',
              'instructions' => 'To show a color highlight behind this layout section, select the theme here.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'none',
                'theme_primary' => 'theme_primary',
                'theme_secondary' => 'theme_secondary',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58d6efde718b4',
          'name' => 'tab_group',
          'label' => 'Tab Group',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_59665df554443',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_58d6efde718b5',
              'label' => 'Panels',
              'name' => 'panels',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => 'field_58d6efde718b6',
              'min' => 0,
              'max' => 0,
              'layout' => 'table',
              'button_label' => 'Add Panel',
              'sub_fields' => array (
                array (
                  'key' => 'field_58d6efde718b6',
                  'label' => 'Panel Title',
                  'name' => 'panel_title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_58d6efde718b7',
                  'label' => 'Panel Content',
                  'name' => 'panel_content',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'full',
                  'media_upload' => 1,
                  'delay' => 0,
                ),
                array (
                  'key' => 'field_58d6efde718b8',
                  'label' => 'Panel Open by Default',
                  'name' => 'panel_open_by_default',
                  'type' => 'true_false',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'message' => 'This panel should be open by default.',
                  'default_value' => 0,
                  'ui' => 1,
                  'ui_on_text' => 'Open',
                  'ui_off_text' => 'Closed',
                ),
              ),
            ),
            array (
              'key' => 'field_58d7173325bee',
              'label' => 'Collapsable Tabs',
              'name' => 'collapsable_tabs',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'message' => 'Allow tabs to be collapsable.',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array (
              'key' => 'field_58d7177125bef',
              'label' => 'Tab Orientation',
              'name' => 'tab_orientation',
              'type' => 'radio',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'horizontal' => 'Horizontal',
                'vertical' => 'Vertical',
              ),
              'allow_null' => 0,
              'other_choice' => 0,
              'save_other_choice' => 0,
              'default_value' => 'horizontal',
              'layout' => 'horizontal',
              'return_format' => 'value',
            ),
            array (
              'key' => 'field_58d6efde718b9',
              'label' => 'Space Before',
              'name' => 'space_before',
              'type' => 'select',
              'instructions' => 'To include space before this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array (
              'key' => 'field_58d6efde718ba',
              'label' => 'Space After',
              'name' => 'space_after',
              'type' => 'select',
              'instructions' => 'To include space after this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
              'return_format' => 'value',
            ),
            array (
              'key' => 'field_59665e0054444',
              'label' => 'Section Highlight',
              'name' => 'section_highlight',
              'type' => 'select',
              'instructions' => 'To show a color highlight behind this layout section, select the theme here.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'none',
                'theme_primary' => 'theme_primary',
                'theme_secondary' => 'theme_secondary',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58d71d187dfd3',
          'name' => 'thumbnail_gallery',
          'label' => 'Thumbnail Gallery',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_59665e0e54445',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_58d71d187dfd9',
              'label' => 'Gallery',
              'name' => 'gallery',
              'type' => 'gallery',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'min' => '',
              'max' => '',
              'insert' => 'append',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array (
              'key' => 'field_58d71d187dfda',
              'label' => 'Space Before',
              'name' => 'space_before',
              'type' => 'select',
              'instructions' => 'To include space before this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array (
              'key' => 'field_58d71d187dfdb',
              'label' => 'Space After',
              'name' => 'space_after',
              'type' => 'select',
              'instructions' => 'To include space after this layout section select the pre-defined amount.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'normal' => 'Normal',
                'extra' => 'Extra',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array (
              'key' => 'field_59665e1954446',
              'label' => 'Section Highlight',
              'name' => 'section_highlight',
              'type' => 'select',
              'instructions' => 'To show a color highlight behind this layout section, select the theme here.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'none',
                'theme_primary' => 'theme_primary',
                'theme_secondary' => 'theme_secondary',
              ),
              'default_value' => array (
                0 => 'none',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;
